### ISSUE TITLE
Add image filter annotation

### ISSUE THREAD

**Issue by Bukashk0zzz** [fre5h/VichUploaderSerializationBundle#4]
What do you think about adding new option "filter" for annotation.
Example:
`@Fresh\VichSerializableField("coverFile", includeHost=false, filter="my_thumb")`

This option will be adding filter to image using [LiipImagineBundle  ](https://github.com/liip/LiipImagineBundle)

**Comment by fre5h** [comment]
Yeap, I thought about it. But the problem is that we cannot make LiipImagineBundle as dependency for this bundle. Because somebody will want to use just image serialization without filtering via imagine. So this feature should be optional, we should check if LiipImagineBundle is enabled and only in this case use filters, otherwise this option should be skipped.

Also we should put LiipImagineBundle to *suggests* section in composer.json not to the *require*.

I think the idea is nice. But I can implement this feature only when be free. If you implement it earlier than me then send pull request to the `develop` branch at first. Also don't forget about tests and updating the README.

**Comment by Bukashk0zzz** [comment]
I think a lot of how to better add this feature to this bundle. But always it looks ugly because of dependency on LiipImagine. So I decided that better to separate image and file fields serialization.
So I create bundle for image serialization [LiipImagineSerializationBundle](https://github.com/Bukashk0zzz/LiipImagineSerializationBundle)
